name: Sanity Check

on: push

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: |
          npm install --legacy-peer-deps
      - name: Lint and tests check
        run: |
          npm run check
